#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.join(__dir__, '..', 'lib')

require 'bitbar/thyme'

status = Bitbar::Thyme::Status.new

puts status.summary
puts '---'
puts status.details
